### ISSUE TITLE
Build binary 7zip_21.02

### ISSUE THREAD

**Issue by teoberi** [jinfeihan57/p7zip#143]
SO: Slackware64-current
gcc/g++ version: 10.3.0

1. Compile and build the binary 7zz
`cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc`

> g++      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC   -o _o/ZstdDecoder.o  ../../Compress/ZstdDecoder.cpp
../../Compress/ZstdDecoder.cpp: In member function ‘virtual LONG NCompress::NZSTD::CDecoder::SetDecoderProperties2(const Byte*, UInt32)’:
../../Compress/ZstdDecoder.cpp:47:30: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of a non-trivial type ‘struct NCompress::NZSTD::DProps’ leaves 2 bytes unchanged [-Werror=class-memaccess]
   47 |     memcpy(&_props, pProps, 3);
      |                              ^
In file included from ../../Compress/ZstdDecoder.cpp:10:
../../Compress/ZstdDecoder.h:34:8: note: ‘struct NCompress::NZSTD::DProps’ declared here
   34 | struct DProps {
      |        ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [../../7zip_gcc.mak:1194: _o/ZstdDecoder.o] Error 1

2. Same error for 7za and 7z.so.
3. Compile and build the binary 7zr
`cd p7zip/CPP/7zip/Bundles/Alone7z && make -f makefile.gcc`

> g++      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC   -o _o/OffsetStream.o  ../../Common/OffsetStream.cpp
../../Common/OffsetStream.cpp: In member function ‘virtual LONG COffsetOutStream::Seek(Int64, UInt32, UInt64*)’:
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [../../7zip_gcc.mak:342: _o/OffsetStream.o] Error 1

**Comment by teoberi** [comment]
Same error for WSL2 -> Ubuntu -> gcc/g++ 9.3.0

**Comment by jinfeihan57** [comment]
Try this:
make -f makefile.gcc CFLAGS=-Wno-maybe-uninitialized

**Comment by jinfeihan57** [comment]
Please, Check this [PR](https://github.com/jinfeihan57/p7zip/commit/b5c86f91b01baadf1090042035a4a657c9db3f8e) and try again.

**Comment by teoberi** [comment]
> Please, Check this [PR](https://github.com/jinfeihan57/p7zip/commit/b5c86f91b01baadf1090042035a4a657c9db3f8e) and try again.

> g++      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC   -o _o/Lz4Decoder.o  ../../Compress/Lz4Decoder.cpp
../../Compress/Lz4Decoder.cpp: In member function ‘virtual LONG NCompress::NLZ4::CDecoder::SetDecoderProperties2(const Byte*, UInt32)’:
../../Compress/Lz4Decoder.cpp:92:30: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of a non-trivial type ‘struct NCompress::NLZ4::DProps’ leaves 2 bytes unchanged [-Werror=class-memaccess]
   92 |     memcpy(&_props, pProps, 3);
      |                              ^
In file included from ../../Compress/Lz4Decoder.cpp:4:
../../Compress/Lz4Decoder.h:31:8: note: ‘struct NCompress::NLZ4::DProps’ declared here
   31 | struct DProps
      |        ^~~~~~
cc1plus: all warnings being treated as errors
make: *** [../../7zip_gcc.mak:1220: _o/Lz4Decoder.o] Error 1

**Comment by jinfeihan57** [comment]
I push a new patch. Please, Check test angin.

**Comment by teoberi** [comment]
> I push a new patch. Please, Check test angin.

Fixed!

The error from the 7zr compilation (point 3 from the first post) now appears when compiling 7zz, ie:
> g++      -O2 -c -Wall -Werror -Wextra  -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC   -o _o/OffsetStream.o  ../../Common/OffsetStream.cpp
../../Common/OffsetStream.cpp: In member function ‘virtual LONG COffsetOutStream::Seek(Int64, UInt32, UInt64*)’:
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   32 |     *newPosition = absoluteNewPosition - _offset;
      |                    ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [../../7zip_gcc.mak:342: _o/OffsetStream.o] Error 1

**Comment by teoberi** [comment]
> Try this:
> make -f makefile.gcc CFLAGS=-Wno-maybe-uninitialized

Result:

> mkdir -p _o
cc -Wno-maybe-uninitialized ../../../../C/7zBuf2.c
/usr/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/10.3.0/../../../../lib64/crt1.o: in function `_start':
/tmp/glibc-2.33/csu/../sysdeps/x86_64/start.S:110: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [../../7zip_gcc.mak:1005: _o/7zBuf2.o] Error 1

**Comment by jinfeihan57** [comment]
cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc CFLAGS=-Wno-maybe-uninitialized
What's wrong here？？？

**Comment by teoberi** [comment]
I don't know, I get the message from the previous post.
It doesn't work but I don't need that option either!

The only problem left in the post is:
https://github.com/jinfeihan57/p7zip/issues/143#issuecomment-842439539

**Comment by jinfeihan57** [comment]
-Werror means Make **all warnings** into errors. It's Ok to delete it. 
It just not perfect.
Still suggest you try "make -f makefile.gcc CFLAGS=-Wno-maybe-uninitialized"

**Comment by jinfeihan57** [comment]
By the way, some default check warnings will only appear in higher version compilers.Just like you used gcc/g++ version: 10.3.0.
It OK working on gcc/g++ version: 7.5.0. (ubuntu1~18.04)

**Comment by teoberi** [comment]
> -Werror means Make **all warnings** into errors. It's Ok to delete it.
> It just not perfect.
> Still suggest you try "make -f makefile.gcc CFLAGS=-Wno-maybe-uninitialized"

I agree that it is not perfect!
I tried compiling with the suggested command but nothing works.
I only get this:

> mkdir -p _o
cc -Wno-maybe-uninitialized ../../../../C/7zBuf2.c
/usr/bin/ld: /usr/lib64/gcc/x86_64-slackware-linux/10.3.0/../../../../lib64/crt1.o: in function `_start':
/tmp/glibc-2.33/csu/../sysdeps/x86_64/start.S:110: undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [../../7zip_gcc.mak:1005: _o/7zBuf2.o] Error 1

**Comment by jinfeihan57** [comment]
> mkdir -p _o
cc -Wno-maybe-uninitialized ../../../../C/7zBuf2.c

Why compile separately  .../../../../C/7zBuf2.c？？？

Just do the following steps：
>git clone ... 
cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc

**Comment by teoberi** [comment]
I return to the only problem left.
Points 1 and 2 of my first post have been resolved.
Point 3 remained, ie:
`cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc`
Result:

> g++ -O2 -c -Wall -Werror -Wextra -DNDEBUG -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fPIC -o _o/OffsetStream.o ../../Common/OffsetStream.cpp
> ../../Common/OffsetStream.cpp: In member function ‘virtual LONG COffsetOutStream::Seek(Int64, UInt32, UInt64*)’:
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> ../../Common/OffsetStream.cpp:32:40: error: ‘absoluteNewPosition’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> 32 | *newPosition = absoluteNewPosition - _offset;
> | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
> cc1plus: all warnings being treated as errors
> make: *** [../../7zip_gcc.mak:342: _o/OffsetStream.o] Error 1

**Comment by teoberi** [comment]
> > mkdir -p _o
> > cc -Wno-maybe-uninitialized ../../../../C/7zBuf2.c
> 
> Why compile separately .../../../../C/7zBuf2.c？？？
> 
> Just do the following steps：
> 
> > git clone ...
> > cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc

That's what I did, I don't compile anything separately.

**Comment by jinfeihan57** [comment]
cd p7zip/CPP/7zip/Bundles/Alone2 && make -f makefile.gcc **CFLAGS=-Wno-maybe-uninitialized**

**Comment by jinfeihan57** [comment]
Maybe you can try [this](https://sourceforge.net/p/sevenzip/discussion/45797/thread/7fe6c21efa/#40a6)

> cd CPP/7zip/Bundles/Alone2
make -j -f ../../cmpl_gcc.mak

**Comment by teoberi** [comment]
Result:
> mkdir -p b/g_x64
asmc -elf64 -DABI_LINUX -Fob/g_x64/ ../../../../Asm/x86/LzmaDecOpt.asm
make: asmc: No such file or directory
make: *** [../../7zip_gcc.mak:1134: b/g_x64/LzmaDecOpt.o] Error 127
make: *** Waiting for unfinished jobs....

**Comment by jinfeihan57** [comment]
> I don't know, I get the message from the previous post.
> It doesn't work but I don't need that option either (CFLAGS=-Wno-maybe-uninitialized)!
> 
> The only problem left in the post is:
> [#143 (comment)](https://github.com/jinfeihan57/p7zip/issues/143#issuecomment-842439539)
> 
> If in the p7zip/CPP/7zip/7zip_gcc.mak file I change line 16
> CFLAGS_WARN_WALL = -Wall -Werror -Wextra -> CFLAGS_WARN_WALL = -Wall -Wextra
> the error occurs but I can successfully compile 7zz.
> I don't know if it's OK like that, I don't think so!
> [7zz.txt](https://github.com/jinfeihan57/p7zip/files/6495403/7zz.txt)

you can try this 

> CFLAGS_WARN_WALL = -Wall -Werror -Wextra -> CFLAGS_WARN_WALL = -Wno-maybe-uninitialized -Wall -Werror -Wextra

or just delete -Werror

> CFLAGS_WARN_WALL = -Wall -Werror -Wextra -> CFLAGS_WARN_WALL = -Wall -Wextra

**Comment by teoberi** [comment]
This solution performs clean compilation without errors.

> CFLAGS_WARN_WALL = -Wall -Werror -Wextra -> CFLAGS_WARN_WALL = -Wno-maybe-uninitialized -Wall -Werror -Wextra

You can check the compilation result (file attached).
If you think it is OK now you can close the thread.

[7zz-final.txt](https://github.com/jinfeihan57/p7zip/files/6495838/7zz-final.txt)

**Comment by teoberi** [comment]
Build 7za, 7zr -> OK
Build 7z.so -> Not OK

> /usr/bin/ld: _o/liblizard.a(lizard_frame.o): relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: _o/liblizard.a(xxhash.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: _o/liblizard.a(lizard_compress.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: _o/liblizard.a(lizard_decompress.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make: *** [../../7zip_gcc.mak:158: _o/7z.so] Error 1

**Comment by jinfeihan57** [comment]
I pushed a commit. you can test it again.

**Comment by teoberi** [comment]
I have already tested and everything is OK!

**Comment by teoberi** [comment]
I think I could close this thread?
